-- Active: 1699019036200@@127.0.0.1@3306@webdocsach
CREATE DATABASE webdocsach
    DEFAULT CHARACTER SET = 'utf8mb4';
    
INSERT INTO book (title, author, release_date, upload_at, cover_image, description) VALUES
        ('One_Piece', 'Eiichiro Oda', '1997-12-12', '2023-10-10', 'one-piece.png', 'One Piece xoay quanh 1 nhóm cướp biển được gọi là Băng Hải tặc Mũ Rơm - Straw Hat Pirates - được thành lập và lãnh đạo bởi thuyền trưởng Monkey D. Luffy. Cậu bé Luffy có ước mơ tìm thấy kho báu vĩ đại nhất, One Piece, của Vua Hải Tặc đời trước Gold D. Roger và trở thành Vua Hải Tặc đời kế tiếp. Ở Việt Nam hiện nay, truyện đang được Nhà xuất bản Thanh Hóa xuất bản nhưng không có bản quyền, với tên gọi là Đảo Hải tặc Cốt truyện: Monkey D. Luffy, 1 cậu bé rất thích hải tặc có ước mơ tìm được kho báu One Piece và trở thành Vua hải tặc - Pirate King. Lúc nhỏ, Luffy tình cờ ăn phải trái quỉ (Devil Fruit) Gomu Gomu, nó cho cơ thể cậu khả năng co dãn đàn hồi như cao su nhưng đổi lại cậu sẽ không bao giờ biết bơi. Sau đó Luffy lại được Shank cứu thoát tuy nhiên ông ta bị mất 1 cánh tay. Sau đấy Shank chia tay Luffy và để lại cho cậu cái mũ rơm (Straw Hat) và nói rằng: "Sau này bao giờ thành cướp biển hãy gặp ta và trả lại nó". Chính lời nói này đã thúc đầy Luffy trở thành 1 cướp biển thật sự.'),
         ('Naruto', 'Kishimoto Masashi', '1990-11-1', '2023-10-10', 'naruto.png','Naruto là một cậu bé có mơ ước trở thành hokage của làng Konoha,được Hokage phong ấn trong người một trong 9 quái vật của thể giới : Cửu vĩ Hồ ly.Vì cho cậu là một con quái vật, ko ai dám chơi với cậu!& Vì muốn được thừa nhận nên rất phá phách.Khi tốt nghiệp trướng ninja, lần đầu tiên cậu đã được thừa nhận và có một người bạn thân là Sasuke.Hai năm sau, Sasuke đã rời bỏ làng lá để đi theo Orochimaru vì muốn đạt được sức mạnh hơn người, và dùng sức mạnh đó để giết người anh của mình.Naruto muốn đem Sasuke trở về, và vì Kakashi ko đủ trình độ nên đã đi theo Jiraiya - một trong tam nin truyền thuyết của Konoha - để học tập thêm cách dùng sức mạnh.Sau hai năm trờ về, Naruto đã 16 tuổi và có nhiều thay đổi! Và những khó khăn nguy hiểm cũng từ đó tăng lên 2 năm sau Sasuke đã trưởng thành...và đúng với cái tên thiên tài Uchiha cậu đã hạ được Orochimaru ( tất nhiên là lúc hắn đang bị ấn chú của Đệ tam làm yếu nhất ) và phong ấn hắn trong người cậu. Cậu cùng Suigetsu , Juugo và Karin thành lập Mãng xà truy tìm Itachi. Naruto Sakura Choiji Sai Ino Shikamaru Kiba Shino....cũng dần trở thành những ninja mạnh mẽ trụ cột của làng lá. Họ đã hạ được 2 thành viên Akatsuki. Cũng như Sasuke hạ được Deidara Sasuke và Itachi đã gặp nhau. Và trận chiến cuối cùng đã xảy ra với chiến thắng của Sasuke. Madara xuất hiện và sự thật về Itachi đã đc hé lộ...bí mật về Gia tộc Uchiha và Làng Lá đã tạo nên bi kịch giữa Sasuke và Itachi. Nhóm Đại Bàng được thành lập kết hợp cùng Akatsuki chính thức truy tìm 9 quái vật có đuôi và bắt đầu kế hoạch trả thù của Sasuke ..........'),
         ('Dragon_Ball', 'Toriyama Akira', '2012-10-10', '2023-11-10', 'dragon-ball.png', 'Một cậu bé có đuôi khỉ được tìm thấy bởi một ông lão sống một mình trong rừng, ông đặt tên là Son Goku và xem đứa bé như là cháu của mình. Một ngày nọ Goku tình cờ gặp một cô gái tên là Bulma trên đường đi bắt cá về, Goku và Bulma đã cùng nhau truy tìm bảy viên ngọc rồng. Các viên ngọc rồng này chứa đựng một bí mật có thể triệu hồi một con rồng và ban điều ước cho ai sở hữu chúng. Trên cuộc hành trình dài đi tìm những viên ngọc rồng, họ gặp những người bạn (Yamcha, Krillin,Yajirobe, Thiên, Giáo tử, Oolong,...) và những đấu sĩ huyền thoại cũng như nhiều ác quỷ. Họ trải qua những khó khăn và học hỏi các chiêu thức võ thuật đặc biệt để tham gia thi đấu trong đại hội võ thuật thế giới được tổ chức hằng năm. Ngoài các sự kiện đại hội võ thuật, Goku và các bạn còn phải đối phó với các thế lực độc ác như Đại vương Pilaf, Quân đoàn khăn đỏ của Độc nhãn tướng quân, Đại ma vương Picollo và những đứa con của hắn. Chiến binh người Saiya: Radiz, Hoàng tử Saiya Vegeta cùng tên cận vệ Nappa. Rồi họ đi đến Namek, gặp rồng thần của Namek; chạm trán Frieza, khi trở về Trái Đất đụng độ Nhóm android sát thủ (các Android 16, 17, 18,19, 20) và sau đó là quái vật từ tương lai Cell, Kẻ thù từ vũ trụ Majin Buu, thần hủy diệt Beerus, các đối thủ từ các vũ trụ song song, Đối thủ mạnh nhất với Goku là Jiren (đến từ vũ trụ 11).'),
         ('Conan','Aoyama Gōshō','1990-10-10','2020-12-12','conan.png','Conan và mọi người được mời tới dự buổi biểu diễn khai trương phòng hòa nhạc Domoto do nghệ sĩ piano lừng danh đã giải nghệ xây dựng. Nhưng rồi nhiều sự việc xảy ra đe dọa tính mạng của nữ ca sĩ thiên tài, nhân vật chính của buổi hòa nhạc! Liệu điều này có liên quan gì tới vụ giết người hàng loạt mới xảy ra đã lần lượt cướp đi sinh mạng các học trò của cựu nghệ sĩ piano...?! Và liệu Conan có hiểu được giai điệu, cũng như những nốt nhạc đầy ác ý được diễn tấu?' ),
         ('Attack_on_Titan', 'Isayama Hajime', '2010-10-05', '2023-10-10', 'attack-on-titan.png', 'Hành động viễn tưởng,Kỳ ảo đen tối,Hậu tận thế'),
         ('Black_Clover', 'Tabata Yūki', '2010-10-05', '2023-10-10', 'black-clover.png', '	Phiêu lưu,kỳ ảo'),
         ('Doremon', 'Fujiko F. Fujio', '2010-10-05', '2023-10-10', 'doremon.png', 'Đôrêmon là một chú mèo máy được Nôbita, cháu ba đời của Nôbita gửi về quá khứ cho ông mình để giúp đỡ Nôbita tiến bộ, tức là cũng sẽ cải thiện hoàn cảnh của con cháu Nôbita sau này. Còn ở hiện tại, Nôbita là một cậu bé luôn thất bại ở trường học, và sau đó là thất bại trong công việc, đẩy gia đình và con cháu sau này vào cảnh nợ nần. Các câu chuyện trong Đôrêmon thường có một công thức chung, đó là xoay quanh những rắc rối hay xảy ra với cậu bé Nôbita lớp bốn, nhân vật chính thứ nhì của bộ truyện. Đôrêmon có một chiếc túi thần kỳ trước bụng với đủ loại bảo bối của tương lai. Cốt truyện thường gặp nhất sẽ là Nôbita trở về nhà khóc lóc với những rắc rối mà cậu gặp phải ở trường hoặc với bạn bè. Sau khi bị cậu bé van nài hoặc thúc giục, Đôrêmon sẽ đưa ra một bảo bối giúp Nôbita giải quyết những rắc rối của mình, hoặc là để trả đũa hay khoe khoang với bạn bè của cậu. Nôbita sẽ lại thường đi quá xa so với dự định ban đầu của Đôrêmon, thậm chí với những bảo bối mới cậu còn gặp rắc rối lớn hơn trước đó. Đôi khi những người bạn của Nôbita (thường là Xêkô hoặc Chaien) lại lấy trộm những bảo bối và sử dụng chúng không đúng mục đích. Tuy nhiên thường thì ở cuối mỗi câu chuyện, những ai sử dụng sai mục đích bảo bối sẽ phải chịu hậu quả do mình gây ra, và người đọc sẽ rút ra được bài học đạo đức từ đó.'),
         ('One_Punch_Man', 'ONE - Murata Yuusuke', '2007-06-21', '2023-10-10', 'one-punch-man.png', 'Một Manga thể loại siêu anh hùng với đặc trưng phồng tôm đấm phát chết luôn... và mang đậm tính chất troll của tác giả.Onepunch-man là câu chuyện của 1 chàng thanh niên 23 tuổi, đang là một nhân viên văn phòng điển trai nghiêm túc và tất nhiên là ế. Không hiểu vì biến cố gì mà tự nhiên lông tóc trên người của anh trụi lủi, sau đó anh mang trong mình khả năng siêu đặc biệt "Đấm phát chết luôn" nhằm bảo vệ trái đất và thành phố nơi anh sinh sống khỏi các sinh vật ngoài không gian (nhưng phá hoại cũng không kém).'),
         ('Jujusu_Kaisen', 'Akutami Gege', '2011-06-21', '2023-10-10', 'jujitsu-kaisen.png', 'Yuuji Itadori là một thiên tài có tốc độ và sức mạnh, nhưng cậu ấy muốn dành thời gian của mình trong Câu lạc bộ Tâm Linh. Một ngày sau cái chết của ông mình, anh gặp Megumi Fushiguro, người đang tìm kiếm vật thể bị nguyền rủa mà các thành viên CLB đã tìm thấy.Đối mặt với những con quái vật khủng khiếp bị "Ám", Yuuji nuốt vật thể bị phong ấn để có được sức mạnh của nó và cứu bạn bè của mình! Nhưng giờ Yuuji là người bị "Ám", và cậu ấy sẽ bị kéo vào thế giới ma quỷ ly kỳ của Megumi và những con quái vật độc ác ...'),
         ('Kimetsu_no_Yaiba','Gotouge Koyoharu','2011-06-21', '2023-10-10','kimetsu-no-yaiba.png', 'Kimetsu no Yaiba  Tanjirou là con cả của gia đình vừa mất cha. Một ngày nọ, Tanjirou đến thăm thị trấn khác để bán than, khi đêm về cậu ở nghỉ tại nhà người khác thay vì về nhà vì lời đồn thổi về ác quỷ luôn rình mò gần núi vào buổi tối. Khi cậu về nhà vào ngày hôm sau, bị kịch đang đợi chờ cậu…'),
         ('Megami_no_Cafe_Terrace', 'Kodansha', '2010-10-05', '2023-10-10', 'quan_cafe_nu_than.png', 'Kasukabe Hayato, đã quay trở lại ngôi nhà xưa của mình là quán cà phê cũ Familia sau 3 năm rời đi và gặp được năm cô gái lạ tự xưng là gia đình của bà mình. Anh ta tuyên bố muốn đóng cửa quán cà phê đang gặp tình cảnh khó khăn nhưng sau cùng lại quyết định trở thành người tiếp quản mới của quán cà phê cùng những cô gái xinh đẹp quyết tâm vực dậy Familia.'),
         ('Record_of_Ragnarok', 'Umemura Shinya', '2010-10-05', '2023-10-10', 'Record_of_Ragnarok.png', 'Các vị thần Hội đồng họp mỗi thiên niên kỷ một lần để quyết định số phận của nhân loại, quyết định rằng lịch sử 7 triệu năm không thể cứu vãn của nhân loại là lý do chính đáng cho sự tuyệt chủng của họ. Nhưng valkyrie Brunhilde đề xuất cho nhân loại một cơ hội cuối cùng để chứng minh giá trị của mình và các vị thần đồng ý tổ chức giải đấu Ragnarök, nơi nhân loại sẽ được tha nếu họ có thể đánh bại các vị thần trong bảy trên mười ba trận đấu. Đại diện của nhân loại là Einherjar, những con người đáng chú ý trong lịch sử, mỗi người được ban cho một valkyrie để trở thành vũ khí mạnh mẽ được thiết kế riêng cho người dùng của họ. Phong cách chiến đấu của cô được gọi là "Volund", có nguy cơ mất mạng nếu người dùng bị giết.'),
         ('Boku_no_Hero_Academia', 'orikoshi Kōhei', '2010-10-05', '2023-10-10', 'default-coverimage.png', 'Trong thế giới mà 80% dân số đều sở hữu những siêu năng lực đặc biệt được gọi là Cá tính (個性 Kosei?) và nó đã được coi như một chuẩn mực của xã hội. Trong một xã hội siêu nhiên đó xuất hiện các "anh hùng" với sức mạnh vượt trội, chiến đấu để bảo vệ thế giới. Midoriya Izuku, một học sinh cấp 2 với mong ước trở thành một người hùng trong tương tai, tuy vậy cậu ta lại là trường hợp đặc biệt. Mặt cậu có quá nhiều tàn nhang, tóc trông như con nhím có chút quê mùa đến khó tả. Thậm chí khi câu chuyện mới bắt đầu, cậu được biết là một người không có siêu năng lực, một trường hợp hiếm hoi trong xã hội siêu thực đó, vì vậy cậu hay bị mọi người gọi là Vô cá tính (無個性 Mu-kosei?). Dù vậy, Midoriya Izuku vẫn thu hút khán giả bởi tính cách lạc quan, yêu đời và thích giúp đỡ người khác. Tuy không có siêu năng lực nhưng cậu vẫn luôn nuôi ước mơ trở thành một Hero đích thực. Cứ tưởng chừng như không còn hy vọng, thì tình cờ Midoriya Izuku có cuộc gặp mặt thần kì với All Might - anh hùng số một thế giới và cũng là thần tượng của Izuku, ông đã ban cho cậu siêu năng lực "One for All". Cũng từ đó câu chuyện ly kì theo chân Izuku cùng với những người bạn mới tại Học viện Anh Hùng, ngôi trường danh tiếng đào đạo các hệ anh hùng tương lai.'),
         ('Dr.STONE', 'Inagaki Riichiro', '2010-10-05', '2023-10-10', 'Dr.STONE.png', 'Sau 1 trận đại dịch không rõ nguồn gốc khiến loài người trên toàn thể địa cầu biến thành đá trải qua mấy ngàn năm sau 2 thanh niên chính của chúng ta là Senkuu và Taiju phá đá thoát ra và bắt đầu lập kế hoạch để cùng nhau tái thiết lập lại thế giới theo cách của họ'),
         ('Gotōbun_no_Hanayome', 'Haruba Negi', '2010-10-05', '2023-10-10', 'Gotōbun_no_Hanayome.png', 'Uesugi Futaro là một học sinh cấp 3 có thành tích xuất sắc tại trường nhưng lại có một cuộc sống khó khăn: không mẹ, không bạn bè, một người bố phải vật lộn với những khoản nợ lớn trong nhà và người em gái lúc nào cũng đói.Một cơ hội của cậu để có thể trả món nợ là làm gia sư, cậu được nhà Nakano giàu có thuê đến nhà dạy học cho con gái của họ. Nhưng cậu nhận ra người cậu phải kèm không phải một mà là chị em sinh 5 cùng trứng, có vẻ ngoài giống hệt nhau nhưng tính cách khác một trời một vực, ai cũng không hứng thú với việc học tập và điểm số. Ban đầu cả năm chỉ coi cậu là một người lạ mặt trong nhà, nhưng sự kiên trì và cần mẫn của Futaro dần thuyết phục những cô gái lao vào việc học, khiến họ có điểm số ngày một tăng và kéo khỏi việc bị trượt.Trong tương lai, Futaro sẽ kết hôn với một trong 5 chị em. Và đó là Yotsuba...'),
         ('Tokyo_Revengers', 'Wakui Ken', '2010-10-05', '2023-10-10', 'default-coverimage.png', 'Hanagaki Takemichi, một chàng trai thất nghiệp 25 tuổi, phát hiện ra rằng bạn gái cũ của cậu, Tachibana Hinata, cũng như em trai cô ấy Tachibana Naoto đã bị giết bởi băng Tokyo Manji (gọi tắt là Touman). Khi Takemichi bị đẩy khỏi nhà ga xuống đường ray, cậu bỗng nhiên quay lại 12 năm trước (2005). Cậu gặp lại Hinata và báo trước cho Naoto biết về cái chết của cả Naoto và chị cậu vào 12 năm sau. Sau khi hai người bắt tay, Takemichi về 12 năm sau, phát hiện ra rằng mình còn sống, được cứu bởi Naoto, giờ là một cảnh sát. Hóa ra Takemichi đã về quá khứ, tạo ra một nghịch lý thời gian nơi Naoto sống. Naoto đoán rằng mỗi lần bắt tay, Takemichi đều sẽ trở về quá khứ đúng 12 năm trước. Sử dụng những hiểu biết 12 năm sau, Takemichi đã thề sẽ cứu Hinata.'),
         ('Nanatsu_no_Taizais', '	Suzuki Nakaba', '2010-10-05', '2023-10-10','default-coverimage.png', 'Câu truyện được bắt đầu tại lục địa Britania, vương quốc Liones, khi các "Thánh Kỵ sĩ" bắt đầu tăng cường vũ khí và sức người để chuẩn bị cho một cuộc chiến tranh mà họ gọi là "Thánh chiến". Vì điều đó, họ đã tiến hành cuộc đảo chính đất nước và đối xử một cách thô bạo với người dân. Elizabeth là tam công chúa của vương quốc, đã trốn ra khỏi cung điện và lên đường tìm nhóm "Nanatsu no Taizai" (Một nhóm hiệp sĩ được gọi là mạnh nhất và bị buộc tội có mưu đồ phản quốc, được cho là đã bị tiêu diệt bởi các "Thánh Kỵ sĩ" vào 10 năm về trước, mặc dù vẫn còn một số người cho rằng họ vẫn còn sống) để nhờ họ đánh bại "Thánh Kỵ sĩ" và giành lại vương quốc. Vì kiệt sức khi phải đi bộ cả ngày đêm và mang bộ giáp để giấu mặt, Elizabeth đã trốn vào trong một quán rượu "Boar Hat" ở gần làng Kaynes. Được chủ quán rượu là Meliodas mời bữa ăn, cô bắt đầu kể câu chuyện về mình. Tuy nhiên, một số người dân đã báo cáo lên Thánh Kỵ Sỹ có một kẻ mặc giáp được cho là một trong những thành viên nhóm "Nanatsu no Taizai" đi đến quán rượu. Và các kỵ sĩ đã phát hiện người mặc giáp đó là Elizabeth và cố gắng bắt cô theo lệnh truy nã của "Đại Hiệp sĩ". Và Meliodas đã cứu thoát cô và tiết lộ thân phận là đội trưởng của nhóm "Nanatsu no Taizai", Ác Long nhân Meliodas, tội đồ của "Phẫn nộ". Hai người đã cùng nhau đi tìm kiếm các thành viên còn lại của nhóm và cố gắng giúp Elizabeth giành lại vương quốc. Dần dần Elizabeth nảy sinh tình cảm với Meliodas.'),
         ('Mairimashita!Iruma-kun', 'Nishi Osamu', '2010-10-05', '2023-10-10', 'Mairimashita!Iruma-kun.png', 'Câu chuyện kể về Suzuki Iruma (鈴木 入間?) một cậu bé 14 tuổi luôn đồng ý mọi lời đề nghị của người khác, vào một ngày nọ cậu bị cha mẹ bán cho một ác ma tên là Sullivan. Ông nhận Iruma là cháu trai và đưa cậu đến ma giới. Ông ghi danh Iruma vào Trường học Ác ma Babyls (悪魔学校バビルス) nơi ông là hiệu trưởng và tại đây, Iruma đã nhanh chóng kết bạn với những ác ma khác là Asmodeus Alice và Valac Clara. Tuy nhiên, Sullivan nói với Iruma rằng đừng bao giờ tiết lộ rằng cậu là con người, vì cậu sẽ bị ăn thịt nếu có ai phát hiện ra điều đó. Iruma sau đó thề sẽ hòa nhập trong thời gian ở Ma giới, mặc dù vậy cậu lại trở nên nổi bật do tất cả các tình huống và những khó khăn khác.'),
         ('Sakamoto_desu_ga', 'Nami Sano', '2010-10-05', '2023-10-10', 'Sakamoto_desu_ga.png', 'Câu chuyện xoay quanh Sakamoto cực kỳ nổi tiếng: một cậu bé hoàn hảo thiên tài được các bạn học và hầu hết giảng viên trong trường yêu mến. trường trung học vì sự lạnh lùng của anh ấy. Bất chấp những tình huống kỳ lạ mà anh ấy thường gặp phải, thường bao gồm những trò đùa do các nam sinh ghen tị trong trường dàn dựng, Sakamoto luôn cố gắng thể hiện một cách hoàn hảo tuyệt đối và kết quả là khiến bản thân thậm chí còn có vẻ ngầu hơn.'),
         ('Fairy_Tail', 'Mashima Hiro', '2010-10-05', '2023-10-10', 'default-coverimage.png','Fairy Tail - một thế giới tràn đầy phép thuật, những pháp sư có thể hô mưa, gọi gió, những con mèo biết bay và những quái vật trong truyền thuyết. Tại vùng đất Fiore, bạn sẽ gặp được tổ chức Fairy Tail, một tổ chức pháp sư có những thành viên vui tính, thú vị và mạnh mẽ nhất. Câu chuyện bắt đầu khi cô gái trẻ Lucy, người có khả năng kêu gọi các tinh linh và ước mơ được gia nhập một tổ chức phù thủy gặp được hỏa pháp sư Natsu đang trên đường tìm kiếm cha nuôi của mình tại thị trấn cảng Harujion… Trong Fairy Tail, bạn sẽ gặp gỡ cặp “chó mèo” Natsu “khạc ra lửa” và “xơi lửa” cùng Gray “băng giá”, Lucy, Erza tài giỏi và “sexy”, theo kèm là những chú mèo ngộ nghĩnh cùng rất nhiều các pháp sư với đủ loại phép thuật kỳ lạ.');
    
INSERT INTO category (description, name)
VALUES 
    ('Thể loại này thường có nội dung về hành động, diễn biến nhanh', 'Hành động'),
    ('Thể loại này thường có nội dung về tình cảm lãng mạn', 'Lãng mạn'),
    ('Thể loại này thường có nội dung về hài hước', 'Hài hước'),
    ('Thể loại này thường có nội dung về kinh dị', 'Kinh dị'),
    ('Thể loại này thường có nội dung về khoa học viễn tưởng', 'Khoa học viễn tưởng'),
    ('Thể loại này thường có nội dung về huyền bí', 'Huyền bí'),
    ('Thể loại này thường có nội dung về thể thao', 'Thể thao'),
    ('Thể loại này thường có nội dung về trinh thám', 'Trinh thám'),
    ('Thể loại này thường có nội dung về phiêu lưu', 'Phiêu lưu'),
    ('Thể loại này thường có nội dung về đời thường', 'Đời thường'),
    ('Thể loại này thường có nội dung về đam mỹ', 'Đam mỹ'),
    ('Thể loại này thường có nội dung về ngôn tình', 'Ngôn tình'),
    ('Thể loại này thường có nội dung về đồng nhân', 'Đồng nhân'),
    ('Thể loại này thường có nội dung về cổ trang', 'Cổ trang'),
    ('Thể loại này thường có nội dung về viễn tưởng', 'Viễn tưởng'),
    ('Thể loại này thường có nội dung về xuyên không', 'Xuyên không'),
    ('Thể loại này thường có nội dung về dị giới', 'Dị giới'),
    ('Thể loại này thường có nội dung về kiếm hiệp', 'Kiếm hiệp'),
    ('Thể loại này thường có nội dung về trọng sinh', 'Trọng sinh'),
    ('Thể loại này thường có nội dung về quân sự', 'Quân sự'),
    ('Thể loại này thường có nội dung về lịch sử', 'Lịch sử'),
    ('Thể loại này thường có nội dung về cổ đại', 'Cổ đại'),
    ('Thể loại này thường có nội dung về tương lai', 'Tương lai'),
    ('Thể loại này thường có nội dung về tâm lý', 'Tâm lý'),
    ('Thể loại này thường có nội dung về võ thuật', 'võ thuật'),
    ('Thể loại này là sự kết hợp giữa thể loại kỳ ảo và thể loại kinh dị với chủ đề tăm tối hơn, giai điệu đáng sợ hơn ', 'kỳ ảo đen tối'),
    ('Thể loại con của khoa học viễn tưởng, các tác phẩm của thể loại này mô tả sự hủy diệt của nền văn minh do một thảm họa tồn vong', 'hậu tận thế'),
    ('Thể loại truyện kỳ ảo là truyện có các yêú tố siêu nhiên như pháp thuật', ' kỳ ảo'),
    ('thể loại này là một nhân vật sở hữu siêu năng lực, những khả năng vượt xa người thường và phù hợp với vai trò của anh hùng, thường sử dụng sức mạnh của mình để giúp thế giới trở nên tốt đẹp hơn hoặc cống hiến hết mình để bảo vệ công lý và chống tội phạm','siêu anh hùng'),
    ('Thể loại này thường có nội dung về khoa học', 'khoa học');

INSERT INTO book_category (book_id, category_id)
VALUES
(1,1),
(1,3),
(1,9),
(2,1),
(2,3),
(2,9),
(2,25),
(4,6),
(4,8),
(4,9),
(3,1),
(3,3),
(3,5),
(3,25),
(5,1),
(5,5),
(5,26),
(5,27),
(6,1),
(6,3),
(6,5),
(6,28),
(7,3),
(7,4),
(7,9),
(8,3),
(8,1),
(8,15),
(9,1),
(9,6),
(9,26),
(10,1),
(10,6),
(10,9),
(10,18),
(11,2),
(11,3),
(11,24),
(12,1),
(12,22),
(12,25),
(13,1),
(13,5),
(13,9),
(13,29),
(14,3),
(14,5),
(14,9),
(14,30),
(15,2),
(15,3),
(15,24),
(16,1),
(16,19),
(17,1),
(17,3),
(17,6),
(18,1),
(18,3),
(18,28),
(19,3),
(20,1),
(20,3),
(20,9);

INSERT INTO chapter (book_id, folder_name, upload_at, title)
VALUES
(1, 'Chapter_1', '2023-10-10', 'Mở màn One Piece'),
(1, 'Chapter_2', '2023-10-10', 'Đại hải trình'),
(1, 'Chapter_3', NOW(), 'Luffy'),
(2, 'Chapter_1', NOW(), 'Cậu bé mang trong mình con cáo chín đuôi'),
(2,'Chapter_2', NOW(), 'Đứa trẻ bị ghét bỏ'),
(3, 'Chapter_0', NOW(), 'Bulma và Son Goku'),
(3, 'Chapter_1', NOW(), 'Ngọc biến mất!'),
(4, 'Chapter_1', '2023-11-10 10:12:20', 'Sát nhân dưới lớp băng cuốn'),
(4, 'Chapter_2', '2023-11-10 10:12:30', 'Bí ẩn của chiếc nhẫn'),
(4, 'Chapter_3', '2023-11-10 10:12:40', 'Cái chết của người mẫu'),
(4, 'Chapter_4', '2023-11-10 10:12:50', 'Mục tiêu của bọn áo đen'),
(5, 'Chapter_1', NOW(), ' Gửi bạn của 2000 năm sau'),
(5, 'Chapter_2', NOW(), 'Bức tường bị phá hủy'),
(5, 'Chapter_3', NOW(), 'Người khổng lồ ăn thịt người'),
(6, 'Chapter_1', NOW(), 'Cậu bé không có ma thuật'),
(6, 'Chapter_2', NOW(), 'Thử thách của Asta'),
(6, 'Chapter_3', NOW(), 'Bắt đầu hành trình của Asta'),
(7, 'Chapter_1', NOW(), 'Cậu bé Nobita và cuộc gặp gỡ kỳ lạ'),
(7, 'Chapter_2', NOW(), 'Chiếc túi thần kỳ'),
(7, 'Chapter_3', NOW(), 'Chuyến du hành đến 22 thế kỷ'),
(7, 'Chapter_4', NOW(), 'Doraemon giúp Nobita lấy lại chiếc máy bay mô hình'),
(7, 'Chapter_5', NOW(), 'Nobita và cuộc thám hiểm dưới biển'),
(7, 'Chapter_6', NOW(), ' Nobita và cuộc thi chạy marathon'),
(7, 'Chapter_7', NOW(), 'Nobita và trận chiến với Jaian và Suneo'),
(7, 'Chapter_8', NOW(), '...'),
(8, 'Chapter_1', NOW(), ' Cậu bé Saitama'),
(8, 'Chapter_2' ,NOW(), 'Saitama và quái vật'),
(8, 'Chapter_3', NOW(), 'Saitama và Hiệp hội Anh hùng');

INSERT INTO rating (book_id, user_id, rate_star) 
VALUES
    (1, 1, 5),
    (1, 1, 4),
    (1, 2, 3),
    (1, 3, 2),
    (1, 4, 1),
    (2, 1, 5),
    (2, 2, 4),
    (2, 3, 3),
    (2, 4, 2),
    (3, 1, 5),
    (3, 2, 4),
    (3, 3, 3),
    (3, 4, 2),
    (4, 1, 1),
    (4, 2, 5),
    (4, 3, 4),
    (4, 4, 3);

INSERT INTO comment (chapter_id, is_edited, user_id, comment_at, content)
VALUES 
(1, 0, 1, '2022-11-10 19:23', 'Hay quá'), 
(2, 0, 1, '2022-11-10 20:10', 'Lù bá thế này ai chơi'),
(3, 0, 1, '2022-11-11 10:06', 'Zoro đẹp trai quá'),
(1, 0, 2, '2023-01-10 18:32', 'Trùm thật sự, 2 chiêu clear làng'),
(3, 1, 3, NOW(), 'Má đánh như cặt'),
(2,0,1,'2022-11-10 19:23','Hay quá'),
(2,0,1,'2022-11-10 20:10','main chính quá mạnh luôn'),
(3,0,4,'2022-11-11 10:06','chap này hay quá'),
(1,0,2,'2023-01-10 18:32','main chính ngầu quá '),
(3,1,3,NOW(),'Má đánh như cặt'),
(1,1,1,now(),'vãi main một đấm chết luôn ạ'),
(1,1,2,now(), 'main có quả mặt trông ngơ vãi'),
(1,0,4,now(),'phim quá hay');