spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webdoctruyen?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: webdoctruyen
    password: password
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    test-connection: true
    username: duy0184466@huce.edu.vn
    password: 
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 558750477314-gsp55lnnjuj7ki5qint3epkr7p8s5dlj.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          github:
            client-id: Iv1.99344991fefa2587
            client-secret: 9cb9852fe6202faffbe10e785e88e1a6fa6b8fa9
      
# Cố định port
server:
  port: 8080

# Ghi log đẹp hơn
logging:
  charset:
    console: UTF-8
  pattern:
    dateformat: yy-MM-dd HH:mm

# cấu hình JWT
application:
  jwt:
    secret: webdoctruyentranh2023tuyentaptruyenlauhaynhat
    issuer: http://localhost:8080
    expiration: 7