spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webdoctruyen
    username: webdoctruyen
    password: password
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        "[format_sql]": true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
# Cố định port
server:
  port: 8080

# Ghi log đẹp hơn
logging:
  charset:
    console: UTF-8
  pattern:
    dateformat: yy-MM-dd HH:mm

# cấu hình JWT
application:
  jwt:
    secret: webdoctruyentranh2023tuyentaptruyenlauhaynhat
    issuer: http://localhost:8080
    expiration: 7