package ptit.edu.vn.entity;

public enum Permission {
    READ_MANGA,
    RATE_MANGA,
    MANAGE_MANGA,
    READ_GENRE,
    MANAGE_GENRE,
    WRITE_COMMENT,
    REPORT_COMMENT,
    MANAGE_COMMENT,
    UPDATE_PROFILE,
    MANAGE_USERS,
    DISABLE_ACCOUNT,
    REQUEST_ACCOUNT_DELETION,
    CHANGE_PASSWORD;
}